[package]
name = "rust-traits-esimerkki"
version = "0.1.0"
edition = "2021"
authors = ["pekka"]
description = "Yksinkertainen esimerkki Rust traits (piirteet) -ominaisuudesta"

[dependencies]
